---
# The base role will do the initial preparation of the autodeploynode.

- name: Install package updates
  yum:
    name: "*"
    state: latest
  ignore_errors: true
  when: not offline

- name: Install required support packages
  yum:
    pkg: "{{ item }}"
    state: present
  with_items: autodeploy_support_pkgs

- name: Install docker-py with pip
  pip:
    name: docker-py
    state: present
    extra_args: "--upgrade"
  when: not offline

- name: Install docker-py with pip when offline
  pip:
    name: docker-py
    state: present
    extra_args: "--index-url=file://{{ packages_path }}simple/"
  when: offline

- name: Create the .ssh directory
  file:
    path: /root/.ssh/
    state: directory

- name: Create SSH Key Pair for root user
  user:
    name: root
    generate_ssh_key: yes

- name: Copy the .ssh/config file
  copy:
    src: config
    dest: /root/.ssh/config
    mode: 0600

- name: Retrieve deployment node public key
  shell: cat /root/.ssh/id_rsa.pub
  register: pub_key

- name: Add deployment node SSH key to node authorized users
  authorized_key:
    user: root
    key: "{{ pub_key.stdout }}"

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Create directories for hanlon
  file:
    path: "{{ item }}"
    state: directory
    setype: svirt_sandbox_file_t
    recurse: true
  with_items:
    - /opt/hanlon
    - /opt/hanlon/image
    - /opt/deploy

- name: Set the correct timezone
  file:
    src: /usr/share/zoneinfo/{{ ntp_timezone }}
    dest: /etc/localtime
    state: link
    force: yes

- name: Configure NTP
  lineinfile:
    backup: yes
    dest: /etc/ntp.conf
    line: "restrict default limited kod nomodify notrap nopeer noquery"
    state: present

- name: Copy the iptables config file
  copy:
    src: iptables
    dest: /etc/sysconfig/iptables

- name: Start & enable iptables, ntpd & docker
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - iptables
    - ntpd
    - docker

- name: Get latest tagged version of Git repos
  uri:
    url: "{{ item.tag }}"
    method: GET
  with_items: git_repos
  register: tags
  when: not offline

- name: Clone source Git repos
  git:
    repo: "{{ item.item.repo }}"
    dest: "{{ projects_base_path }}/{{ item.item.name }}"
    accept_hostkey: yes
    version: "{{ item.json[0].name }}"
  ignore_errors: true
  with_items: tags.results
  when: not offline
