---
language: python
python: "2.7"
sudo: false

install:
  # Install Ansible.
  - pip install ansible==1.9.4

script:
  - cd ansible && python travis_parse_yaml.py
      initial_stage.yml
      main.yml
      site_discovery.yml
      site_docker.yml
      stage_resources.yml
