---
language: python
python: "2.7"
sudo: false

install:
  # Install Ansible.
  - pip install ansible

script:
  - cd ansible && python travis_parse_yaml.py main.yml site_discovery.yml site_docker.yml
