---
- name: Setup kragle
  hosts: localhost
  gather_facts: false
  tasks:

  - name: install support packages
    yum: pkg={{item}} state=present
    with_items:
      - ntp
      - vim
      - dhcp
      - wget
      - docker
      - python-pip
      - sshpass
      - iptables-services

  - name: install docker-py
    pip:
      name: docker-py
      state: present
      extra_args: "--upgrade"

  - name: copy .ssh/config
    copy:
      src: files/config
      dest: /root/.ssh/config
      mode: 600

  - name: disable firewalld
    service:
      name: firewalld
      state: absent
      enabled: no

  - name: create directories for hanlon
    file:
      path: "{{item}}"
      state: directory
      setype: svirt_sandbox_file_t
      recurse: true
    with_items:
      - /opt/hanlon
      - /opt/hanlon/image
      - /opt/deploy

  - name: get the hanlon microkernel image
    get_url:
      url: https://github.com/csc/Hanlon-Microkernel/releases/download/v2.0.1/hnl_mk_prod-image.2.0.1.iso
      dest: /opt/hanlon/image

  - name: copy iptables config file
    copy:
      src: files/iptables
      dest: /etc/sysconfig/iptables

  - name: start & enable services
    service:
      name: "{{item}}"
      enabled: yes
      state: started
    with_items:
      - docker
      - iptables

  - name: clone repos from git
    git:
      repo: "{{item.repo}}"
      dest: "/root/{{item.name}}"
      accept_hostkey: true
    with_items:
      - {name: "wiley", repo: "git://github.com/csc/wiley"}
      - {name: "slimer", repo: "git://github.com/csc/slimer"}
      - {name: "ansible-scaleio", repo: "git://github.com/csc/ansible-scaleio"}

