---
- name: Setup kragle
  hosts: localhost
  tasks:

  - name: install support packages
    yum: pkg={{item}} state=present
    with_items:
      - ntp
      - vim
      - dhcp
      - wget
      - docker
      - python-pip
      - sshpass
      - iptables-services

  - name: install docker-py
    pip: name=docker-py state=present extra_args=update

  - name: copy .ssh/config
    copy: source=/files/config dest=~/.ssh/config

  - name: change file owner
    file: path:/root/.ssh/config mode=600

  - name: disable firewalld
    service: name=firewalld state=absent enabled=no

  - name: create directories for hanlon
    file: path={{item}} state=directory
    with_items:
      - /opt/hanlon
      - /opt/hanlon/image
      - /opt/deploy

  - name: get the hanlon microkernel image
    get_url: url=https://github.com/csc/Hanlon-Microkernel/releases/download/v2.0.1/hnl_mk_prod-image.2.0.1.iso dest=/opt/hanlon/image

  - name: copy iptables config file
    copy: source=/files/iptables dest=/etc/sysconfig/iptables

  - name: start & enable services
    service: name={{item}} enabled=yes state=started
    with_items:
      - docker
      - iptables-services

  - name: change security context
    command: chcon -Rt svirt_sandbox_file_t /opt/hanlon

  - name: clone repos from git
    git: repo={{item}} dest=/root
    with_items:
      - git://github.com/csc/wiley
      - git://github.com/csc/slimer
      - git://github.com/csc/ansible-scaleio

