---
# The createrepo role will create an offline http repo for use when internet connectivity is not available.

- name: Create offline HTTP repo directory
  file:
    path: "/var/www/html/repo"
    state: directory

- name: Copy offline repo file to http directory
  copy:
    src: "{{ rpm_path }}/"
    dest: "/var/www/html/repo"

- name: Create offline HTTP repository
  command: createrepo "/var/www/html/repo"

- name: Create repo file to provide to hosts
  template:
    src: offline.repo.j2
    dest: "/var/www/html/repo/offline.repo"

- name: Start the httpd service
  service:
    name: httpd
    state: restarted
    enabled: yes
