---
# The createrepo role will create an offline http repo for use when internet connectivity is not available.

- name: Create offline repo file to provide to hosts
  template:
    src: offline.repo.j2
    dest: "{{ rpm_path }}"

- name: Create offline repo config for httpd
  template:
    src: offline_repo.conf
    dest: "/etc/httpd/conf.d/"

- name: Start the httpd service
  service:
    name: httpd
    state: restarted
    enabled: yes
