---
# This play is part of the prep-projects role and will check for the necessary files needed by the
# dcaf-bada project. If they are not present it will get them or fail with a message.

- name: Change the permissions on the minimize-rhel-iso.sh file
  file:
    path: "{{ projects_base_path }}/dcaf-bada/scripts/minimize-rhel-iso.sh"
    mode: 0755

- name: Check if RHEL minimized image is in the resources directory
  stat:
    path: "{{ iso_path }}/{{ hnl_rhel_min_image }}"
  register: image_resource

- name: Create the Hanlon RHEL minimized ISO file if missing
  shell: "{{ projects_base_path }}/dcaf-bada/scripts/minimize-rhel-iso.sh -i {{ iso_path }}/{{ rhel_iso_image }} -o {{ iso_path }}/{{ hnl_rhel_min_image }}"
  when: not (image_resource.stat.exists)

- name: Check if RHEL minimized image is in the Hanlon image directory
  stat:
    path: "{{ hnl_mk_local_path }}/{{ hnl_rhel_min_image }}"
  register: image_hanlon

- name: Copy RHEL minimized image to the Hanlon image directory
  copy:
    src: "{{ iso_path }}/{{ hnl_rhel_min_image }}"
    dest: "{{ hnl_mk_local_path }}"
  when: not (image_hanlon.stat.exists)


