---
# This playbook will verify the source files are copied from the usb drive to the autodeploynode.

- name: Check if source CSC projects exist
  stat:
    path: "{{autodeploynode_base_path}}/{{item}}"
  with_items: project_files
  register: git_present

- name: Copy source git files when offline
  copy: 
    src: "{{item.invocation.module_complex_args.path}}"
    dest: "{{autodeploynode_base_path}}"
  with_items: git_present.results
  when: not {{item.stat.exists}}
     
- name: Check if source ISO files exist
  stat:
    path: "{{iso_path}}/{{item}}"
  with_items: iso_files
  register: iso_present 

- name: Copy source ISO files when offline
  copy:
    src: "{{item.invocation.module_complex_args.path}}"
    dest: "{{iso_path}}"
  with_items: iso_present.results
  when: not {{item.stat.exists}}

- name: Check if source docker files exist
  stat:
    path: "{{docker_path}}/{{item}}"
  with_items: docker_files
  register: docker_present

- name: Copy source docker files when offline
  copy:
    src: "{{item.invocation.module_complex_args.path}}"
    dest: "{{docker_path}}"
  with_items: docker_present.results
  when: not {{item.stat.exists}}

- name: Copy source python package files when offline
  copy:
    src: "{{usb_packages_path}}"
    dest: "{{packages_path}}"

- set_fact:
    contents: "{{ lookup('file', '/home/kragle/wiley/docs/final-rpm-list.txt') }}"

- name: Copy Source Red Hat RPMs when offline
  copy:
    src: "{{usb_rpms_path}}/{{item}}.rpm"
    dest: "{{rpm_path}}"
  with_items: contents.splitlines()

- name: Check if source scaleio files exist
  stat:
    path: "{{item}}"
  with_fileglob:
    - "{{usb_scaleio_path}}/*.zip"
  register: scaleio_present

- name: Copy source scaleio files when offline
  copy:
    src: "{{item.invocation.module_complex_args.path}}"
    dest: "{{scaleio_path}}"
  with_items: scaleio_present.results
  when: not {{item.stat.exists}}

