---
# This play will download the public DCAF source projects to the usb drive. All other plays will be run from those projects. At this point ansible has been
# manually installed but there are not any project repos available. This play will call another play from the 'Kragle' project on the usb drive.

- name: Download the Kragle source repo
  hosts: localhost
  gather_facts: false

  vars:
    autodeploy_user: autodeploy
    usb_path: /mnt/sdb/autodeploy
    usb_projects_path: "{{ usb_path }}/projects"
    usb_resources_path: "{{ usb_path }}/resources"

    git_repos:
      - { name: "kragle", repo: "git://github.com/csc/kragle", tag: "https://api.github.com/repos/csc/kragle/tags" }
      - { name: "slimer", repo: "git://github.com/csc/slimer", tag: "https://api.github.com/repos/csc/slimer/tags" }
      - { name: "ansible-scaleio", repo: "git://github.com/csc/ansible-scaleio", tag: "https://api.github.com/repos/csc/ansible-scaleio/tags" }

  tasks:

    - name: Create the staging directories on the usb hard drive
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ autodeploy_user }}"
      with_items:
        - "{{ usb_projects_path }}"
        - "{{ usb_resources_path }}"

    - name: Determine the latest tagged versions of public source Git repos
      uri:
        url: "{{ item.tag }}"
        method: GET
      with_items: git_repos
      register: tags

    - name: Clone the public project repos from Git
      git:
        repo: "{{ item.item.repo }}"
        dest: "{{ usb_projects_path }}/{{ item.item.name }}"
        accept_hostkey: yes
        version: "{{ item.json[0].name }}"
      ignore_errors: true
      with_items: tags.results

