---
- name: Base configure dcaf-abe
  hosts: all
  gather_facts: true
  roles:
    - base
    - dcaf-abe-packer

- include: /tmp/packer-provisioner-ansible-local/site_docker.yml
- include: /tmp/packer-provisioner-ansible-local/site_discovery.yml
  vars:
    packer: true
