---
- name: Base configure kragle
  hosts: all
  gather_facts: true
  roles:
    - base
    - kragle-packer

- include: /tmp/packer-provisioner-ansible-local/playbooks/site_docker.yml 
- include: /tmp/packer-provisioner-ansible-local/playbooks/site_discovery.yml 
