---
# This playbook sets up the environment for discovery of all nodes
- name: Configure deployment node for site discovery
  hosts: localhost
  vars:
    packer: false
  roles:
    - dhcp-server

  tasks:

    - name: Check for local copy of Hanlon Microkernel
      stat:
        path: "{{ hnl_mk_local_path }}{{ hnl_mk_image }}"
      register: hnl_mk

    - name: Download Hanlon Microkernel
      get_url:
        url: "{{ hnl_mk_source }}{{ hnl_mk_image }}"
        dest: "{{ hnl_mk_local_path }}"
      when: not hnl_mk.stat.exists

    - name: Add a Microkernel Image to Hanlon
      hanlon_image:
        base_url: "{{ hanlon_base_url }}"
        type: mk
        path: "{{ hnl_mk_path }}"
      when: not packer

    - name: Add a Discover Only Model to Hanlon
      hanlon_model:
        base_url: "{{ hanlon_base_url }}"
        template: discover_only
        label: discover_only_model
      register: model
      when: not packer

    - name: Add a Discover Only Policy to Hanlon
      hanlon_policy:
        base_url: "{{ hanlon_base_url }}"
        policy_template: discover_only
        label: discover_only_policy
        model_uuid: "{{ model.uuid }}"
        is_default: true
      when: not packer
