---
# This playbook will prepare the staging node and retrieve the automation resources for the autodeploynode.
# The resources will be staged on a usb drive in ../autodeploy/projects and ../autodeploy/resources directories.

- name: Prepare the staging node
  gather_facts: true
  hosts: localhost

  vars_files:
    - /opt/autodeploy/projects/kragle/ansible/inventory/group_vars/all.yml

  tasks:

    - name: install support packages
      yum:
        pkg: "{{ item }}"
        state: present
      with_items: autodeploy_support_pkgs
      tags: pkgs

    - name: install support packages with pip
      pip:
        name: "{{ item }}"
        state: present
        extra_args: "--upgrade"
      with_items: pip_pkgs
      tags: pkgs

    - name: Create the staging directories on the usb hard drive
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ autodeploy_user }}"
      with_items:
        - "{{ usb_projects_path }}"
        - "{{ usb_resources_path }}"
      tags: paths

    - name: Create the resource directories in the staging directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ usb_docker_path }}"
        - "{{ usb_iso_path }}"
        - "{{ usb_packages_path }}"
        - "{{ usb_rpm_path }}"
        - "{{ usb_scaleio_path }}"
      tags: paths

    - name: Download the private project repo from Git
      selenium:
        url: "{{ private_git_url }}"
        username: "{{ git_user }}"
        password: "{{ git_pass }}"
        username_element_id: login_field
        password_element_id: password
        download_directory: "{{ usb_projects_path }}/wiley/"
      tags: git

    - name: Download the Hanlon microkernel image
      get_url:
        url: "{{ hnl_mk_source }}{{ hnl_mk_image }}"
        dest: "{{ usb_iso_path }}"
      tags: iso

# There two separate selenium downloads here because the authtoken on the link will time out
    - name: Find the RHEL DVD ISO file url
      selenium:
        url: "{{ rhel_download_url }}"
        username: "{{ rhn_user }}"
        password: "{{ rhn_pass }}"
        username_element_id: username
        password_element_id: password
        xpath: '//*[contains(@href,"{{ rhel_iso_image }}")]'
      register: rhel_get_url
      tags: iso

    - name: Download the RHEL DVD ISO file
      get_url:
        url: "{{ rhel_get_url.url }}"
        dest: "{{ usb_iso_path }}"
      tags: iso

# There two separate selenium downloads here because the authtoken on the link will time out
    - name: Find the Red Hat KVM Guest Image file url
      selenium:
        url: "{{ rhel_download_url }}"
        username: "{{ rhn_user }}"
        password: "{{ rhn_pass }}"
        username_element_id: username
        password_element_id: password
        xpath: '//*[contains(@href,"{{ kvm_guest_image }}")]'
      register: kvm_get_url
      tags: iso

    - name: Download the KVM Guest Image file
      get_url:
        url: "{{ kvm_get_url.url }}"
        dest: "{{ usb_iso_path }}"
      tags: iso

    - name: Download the Red Hat RPMs
      shell: yumdownloader --downloadonly --destdir={{ usb_rpm_path }} $(cat {{ usb_rpm_list }})
      tags: repo

    - name: Create the local offline repository
      command: createrepo "{{ usb_rpm_path }}"
      tags: repo

    - name: Mirror docker-py and its dependencies
      command: pip2tgz "{{ usb_packages_path }}" docker-py
      tags: docker

    - name: Create the PyPi-compatible "simple" package
      command: dir2pi "{{ usb_packages_path }}"
      tags: docker

    - name: Start and enable the docker service
      service:
        name: docker
        enabled: yes
        state: started
      tags: docker

    - name: Pull the project docker images from the docker registry
      docker:
        docker_api_version: "{{ docker_api_version }}"
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: present
      with_items:
        - { name: hanlon-mongo, image: mongo }
#        - { name: hanlon-cassandra, image: tobert/cassandra }
        - { name: hanlon-server, image: cscdock/hanlon }
        - { name: hanlon-atftpd, image: cscdock/atftpd }
      tags: docker

    - name: Save container image to usb drive
      shell: docker save docker.io/"{{ item.image }}" > "{{ usb_docker_path }}/{{ item.tar_file }}"
      with_items:
        - { image: cscdock/hanlon, tar_file: cscdock_hanlon.tar }
        - { image: cscdock/atftpd, tar_file: cscdock_atftpd.tar }
        - { image: mongo, tar_file: mongo.tar }
      tags: docker

    - name: Download ScaleIO files for ansible-scaleio project
      get_url:
        url: "{{ scaleio_source_url }}"
        dest: "{{ usb_scaleio_path }}"
      tags: scaleio
